categories = [
    {"fr": "Fiction", "en": "Fiction"},
    {"fr": "Science", "en": "Science"},
    {"fr": "Mathématiques", "en": "Mathematics"},
    {"fr": "Technologie", "en": "Technology"},
    {"fr": "Informatique", "en": "Computers"},
    {"fr": "Histoire", "en": "History"},
    {"fr": "Biographies", "en": "Biography"},
    {"fr": "Philosophie", "en": "Philosophy"},
    {"fr": "Psychologie", "en": "Psychology"},
    {"fr": "Religion", "en": "Religion"},
    {"fr": "Art", "en": "Art"},
    {"fr": "Musique", "en": "Music"},
    {"fr": "Arts du spectacle", "en": "Performing Arts"},
    {"fr": "Poésie", "en": "Poetry"},
    {"fr": "Théâtre", "en": "Drama"},
    {"fr": "Bandes dessinées", "en": "Comics"},
    {"fr": "Romans jeunesse", "en": "Juvenile Fiction"},
    {"fr": "Documentaires jeunesse", "en": "Juvenile Nonfiction"},
    {"fr": "Romans ados", "en": "Young Adult Fiction"},
    {"fr": "Documentaires ados", "en": "Young Adult Nonfiction"},
    {"fr": "Éducation", "en": "Education"},
    {"fr": "Linguistique", "en": "Linguistics"},
    {"fr": "Langues étrangères", "en": "Foreign Language Study"},
    {"fr": "Critique littéraire", "en": "Literary Criticism"},
    {"fr": "Littérature", "en": "Literature"},
    {"fr": "Économie et affaires", "en": "Business & Economics"},
    {"fr": "Droit", "en": "Law"},
    {"fr": "Sciences politiques", "en": "Political Science"},
    {"fr": "Sciences sociales", "en": "Social Science"},
    {"fr": "Santé et bien-être", "en": "Health & Fitness"},
    {"fr": "Médecine", "en": "Medical"},
    {"fr": "Développement personnel", "en": "Self-Help"},
    {"fr": "Cuisine", "en": "Cooking"},
    {"fr": "Maison et jardin", "en": "House & Home"},
    {"fr": "Famille et relations", "en": "Family & Relationships"},
    {"fr": "Voyage", "en": "Travel"},
    {"fr": "Sports et loisirs", "en": "Sports & Recreation"},
    {"fr": "Nature", "en": "Nature"},
    {"fr": "Animaux", "en": "Pets"},
    {"fr": "Jardinage", "en": "Gardening"},
    {"fr": "Bricolage et loisirs créatifs", "en": "Crafts & Hobbies"},
    {"fr": "Jeux", "en": "Games"},
    {"fr": "Antiquités et collections", "en": "Antiques & Collectibles"},
    {"fr": "Faits divers", "en": "True Crime"},
    {"fr": "Science-fiction", "en": "Science Fiction"},
    {"fr": "Fantastique", "en": "Fantasy"},
    {"fr": "Horreur", "en": "Horror"},
    {"fr": "Policier", "en": "Mystery"},
    {"fr": "Thriller", "en": "Thriller"},
    {"fr": "Romance", "en": "Romance"},
    {"fr": "Aventure", "en": "Adventure"},
    {"fr": "Référence", "en": "Reference"}
]